#! /usr/bin/env python
import numpy as np 
import pyfits

hdulist = pyfits.open('3C120_peak_hard.BasicMaps.fits')
hdulist.info()
_ExpOn=hdulist[1].data
_ExpOff=hdulist[2].data
_NOn=hdulist[3].data
_NOff=hdulist[4].data
hdulist.close()

np.savetxt("On.dat",_NOn,fmt='%1.2f')
np.savetxt("Off.dat",_NOff,fmt='%1.2f')
np.savetxt("ExpOn.dat",_ExpOn,fmt='%1.2f')
np.savetxt("ExpOff.dat",_ExpOff,fmt='%1.2f')
